import Head from "next/head";
import "../styles/globals.scss";
import type { AppProps } from "next/app";
import GoogleAnalitics from "../utils/GoogleAnalitics";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import styles from "../styles/Home.module.scss";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>База медичних фейків</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:image"
          content="https://inthepocket.tech/api/og-image?name=Next.js&stage=adopt"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Header />
        <GoogleAnalitics />
        <main className={styles.mainContent}>
          <Component {...pageProps} />
        </main>
        <Footer />
      </div>
    </>
  );
}

export default MyApp;
